# Generated by Django 6.1.1 on 2026-09-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Credit Card / Vodafone Cash / Instapay')], default='COD', max_length=20),
        ),
    ]
