# Generated by Django 6.1.1 on 2026-09-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
