# Generated by Django 6.1.1 on 2026-09-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_is_best_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bags', 'Bags'), ('wallets', 'Wallets'), ('belts', 'Belts')], max_length=100),
        ),
    ]
