# Generated by Django 6.1.1 on 2026-09-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_is_on_sale_product_original_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
    ]
