# Generated by Django 6.1.1 on 2026-09-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_city_order_governorate_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=100, unique=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_company', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
