# Generated by Django 6.1.1 on 2026-09-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='content',
        ),
        migrations.AddField(
            model_name='policy',
            name='confirmation_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='confirmation_title',
            field=models.CharField(default='Order Confirmation', max_length=200),
        ),
        migrations.AddField(
            model_name='policy',
            name='damaged_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='damaged_title',
            field=models.CharField(default='Damaged or Incorrect Items', max_length=200),
        ),
        migrations.AddField(
            model_name='policy',
            name='inspection_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='inspection_title',
            field=models.CharField(default='Order Inspection', max_length=200),
        ),
        migrations.AddField(
            model_name='policy',
            name='no_refunds_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='no_refunds_title',
            field=models.CharField(default='No Refunds or Exchanges', max_length=200),
        ),
        migrations.AddField(
            model_name='policy',
            name='refused_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='refused_title',
            field=models.CharField(default='Refused Orders', max_length=200),
        ),
    ]
