# Generated by Django 6.1.1 on 2026-09-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
