# Generated by Django 6.1.1 on 2026-09-17 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_productvariant_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
    ]
